
### Data Set

The data set for this assignment is called **`fastfood`**. See the [fastfood documentation](https://www.openintro.org/data/index.php?data=fastfood) for more info.

```{r}

rm(list = ls())

library(tidyverse)
library(openintro)

```

```{r}

fastfood

```

```{r}

Q0.1 <- fastfood %>%
  select(restaurant, calories) %>%
  group_by(restaurant) %>% 
  slice_max(calories, n=3) %>%
  as.data.frame()

Q0.1

```

```{r}

Q0.2 <- fastfood %>%   
  select(restaurant, calories) %>%   
  filter(calories>1000) %>%    
  group_by(restaurant) %>%    
  summarise(item_count = n()) %>%    
  as.data.frame() 

Q0.2

```

```{r}

fastfood
Q1 <- fastfood |>
        filter(restaurant %in% c("Burger King","Chick Fil-A")) |>
        arrange(desc(calories)) |>
        select(item) |>
        head(1) |>
        as.data.frame()

Q1

```

```{r}

Q2 <- fastfood |>
        filter(restaurant %in% c("Subway")) |>
        summarise(avg_sugar = mean(sugar, na.rm=TRUE)) |>
        as.data.frame()

Q2

```

```{r}

Q3 <- fastfood |>
  filter(restaurant == "Taco Bell") %>%
  summarise(avg_calories = mean(calories, na.rm = TRUE)) |>
  as.data.frame()

Q3

```

```{r}

Q4 <- fastfood |>
  group_by(restaurant,item) |>
  summarise(fatXsugar = total_fat * sugar) |>
  arrange(desc(fatXsugar)) |>
  head(3) |>
  as.data.frame()

Q4

```

```{r}

Q5 <- fastfood |>
  group_by(restaurant) |>
  summarise(avg_sat_fat = mean(sat_fat, na.rm = TRUE)) |>
  filter(avg_sat_fat > 10) |>
  nrow() |>
  as.data.frame()

Q5

```
