
### Data Set

The data set for this assignment is called **`pizza`**. It is from Introduction to [***Statistics and Data Analysis - with exercises, solutions and applications in R***](https://chris.userweb.mwn.de/book/) by by Christian Heumann, Michael Schomaker and Shalabh.

```{r}

rm(list = ls())

library(tidyverse) 

pizza <- read_csv('pizza.csv')

```

```{r}

pizza

```

```{r}

Q1 <- pizza |>
  group_by(driver) |>
  filter(
    free_wine == 1 &
    discount_customer == 1 &
    pizzas > 4
  ) |>
  select(driver) |>
  as.data.frame()

Q1

```

```{r}

Q2 <- pizza |>
      mutate(ratio = bill / pizzas) |>
      summarise(mean_ratio = round(mean(ratio),2)) |>
      as.data.frame()

Q2

```

```{r}

Q3 <- pizza |>
        group_by(day) |>
        summarise(var_pizzas = round(var(pizzas),2)) |>
        as.data.frame()

Q3

```

```{r}

Q4 <- pizza |>
        group_by(operator) |>
        arrange(desc(bill)) |>
        select(operator) |>
        head(1) |>
        as.data.frame()

Q4

```

```{r}

Q5 <- pizza |>
  group_by(day,driver) |>
  summarise(count = sum(free_wine, na.rm = TRUE), .groups = 'drop') |>
  filter(count == max(count)) |>
  as.data.frame()

Q5

```
